apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: email-consumer-service
  path: ./apps/dev
