apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: email-consumer-service
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  secretRef:
    name: email-consumer-service
  url: ssh://git@github.com/brandon-parker-code/email-consumer-service-gitops
